baseURL = 'https://jmeiss.me/'
languageCode = 'en-us'
title = 'Jeremy Meiss | DevEx and DevRel Leader'
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 0

ignoreLogs = ['shortcode-twitter-getremote']

enableGitInfo = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
