baseURL = 'https://jmeiss.me/'
languageCode = 'en-us'
title = 'Jeremy Meiss | DevEx and DevRel Leader'
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 0

ignoreLogs = ['shortcode-twitter-getremote']

enableGitInfo = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[frontmatter]
  date = ['date', 'publishDate', 'pubdate', 'lastmod', 'modified']
  expiryDate = ['expiryDate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishDate', 'pubdate']
  publishDate = ['publishDate', 'pubdate', 'date']
