languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Jeremy Meiss"
copyright = "&copy; 2024-25. Jeremy Meiss. All rights reserved."

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Personal website of Jeremy Meiss, DevEx and DevRel Leader."

[params.author]
  name = "Jeremy Meiss"
  image = "img/author.jpg"
  headline = "DevEx and DevRel Leader"
  bio = "A little bit about you"
  links = [
  #   { email = "mailto:hello@your_domain.com" },
    { link = "https://jmeiss.me/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
    { bluesky = "https://bsky.app/profile/jerdog.dev" },
  #   { codepen = "https://codepen.io/username" },
    { dev = "https://dev.to/jerdog" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/jerdog" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
    { keybase = "https://keybase.io/jerdog" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/jeremymeiss" },
    { mastodon = "https://hachyderm.io/@jerdog" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
    { threads = "https://threads.net/@therealjerdog" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
    { x-twitter = "https://twitter.com/iamjerdog" },
  #   { youtube = "https://youtube.com/username" },
  #   { xing = "https://xing.com/profile/username" },
  ]
